### ISSUE TITLE
ITK reference error. 

### ISSUE THREAD

**Issue by dyt811** [DevelopmentalImagingMCRI/mantis#1]
tclap-code @ 4970b7e cannot be cloned. Not sure why... bad dependency?

**Comment by dyt811** [comment]
Not sure where this code come from but the reference to "git://itk.org/ITK.git" will cause issue during compilation while it should be "http://itk.org/ITK.git". I think it is from: 
ITK-prefix\src\ITK-stamp\ITK-gitinfo.txt and 
ITK-prefix\tmp\ITK-gitclone.cmake

**Comment by richardbeare** [comment]
Hi,
Sorry we never responded to this - for some reason I never received a notification. Are you having problems with these errors still? I have just built on a system that did not have my normal github certificates installed without any issue.
