### ISSUE TITLE
Failed: Simple watershed scalping

### ISSUE THREAD

**Issue by francescomarialorusso** [DevelopmentalImagingMCRI/mantis#10]
Hi,
when I try to run the simple watershed scalping batch function of Mantis I get the following error:

2-May-2020 14:12:16 - Running 'Simple watershed scalping'
/usr/local/MATLAB/R2019b/toolbox/spm12/toolbox/mantis/ITKStuff/Build.GLNXA64/MANTiS-build/bin/neonateScalper: /usr/local/MATLAB/R2019b/sys/os/glnxa64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /usr/local/MATLAB/R2019b/toolbox/spm12/toolbox/mantis/ITKStuff/Build.GLNXA64/MANTiS-build/bin/neonateScalper)
/usr/local/MATLAB/R2019b/toolbox/spm12/toolbox/mantis/ITKStuff/Build.GLNXA64/MANTiS-build/bin/neonateScalper: /usr/local/MATLAB/R2019b/sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/MATLAB/R2019b/toolbox/spm12/toolbox/mantis/ITKStuff/Build.GLNXA64/MANTiS-build/bin/neonateScalper)
02-May-2020 14:12:16 - Failed  'Si
[scalping_error.zip](https://github.com/DevelopmentalImagingMCRI/mantis/files/4567674/scalping_error.zip)

mple watershed scalping'
Error using read_hdr (line 39)
Error reading header file "/home/francesco/Desktop/prova_registrazione/sct2_10.nii".
In file "/usr/local/MATLAB/R2019b/toolbox/spm12/@nifti/private/read_hdr.m" (v7504), function "read_hdr" at line 39.
In file "/usr/local/MATLAB/R2019b/toolbox/spm12/@nifti/nifti.m" (v7758), function "nifti" at line 26.
In file "/usr/local/MATLAB/R2019b/toolbox/spm12/spm_get_space.m" (v6379), function "spm_get_space" at line 18.
In file "/usr/local/MATLAB/R2019b/toolbox/spm12/toolbox/mantis/mantisCopyHeader.m" (???), function "mantisCopyHeader" at line 5.
In file "/usr/local/MATLAB/R2019b/toolbox/spm12/toolbox/mantis/cg_mantis_scalper_run.m" (???), function "cg_mantis_scalper_run" at line 25.

The following modules did not run:
Failed: Simple watershed scalping

I have attached the report file of the error.
First I thought it was a problem with my test nifti image, but when I try to open it with other applications (spm12 itself, Mango, R) I don't encounter any problems or errors.
Is there a fix for that?
Thanks and all the best
Francesco

**Comment by richardbeare** [comment]
This sort of error, which appears to be suggesting wrong versions of system libraries, may result from building mantis on a different system to the one which it is being run on, or upgrading the host OS after the mantis build. Have a try of the following to help isolate the problem.

First test the scalper from the shell (rather than from inside matlab).

`/usr/local/MATLAB/R2019b/toolbox/spm12/toolbox/mantis/ITKStuff/Build.GLNXA64/MANTiS-build/bin/neonateScalper`

If this returns the same error then likely a rebuild of mantis will fix the problem.

**Comment by francescomarialorusso** [comment]
Hi,
thanks for your help. I tried the terminal command but I ran in the following error:

 /usr/local/MATLAB/R2019b/toolbox/spm12/toolbox/mantis/ITKStuff/Build.GLNXA64/MANTiS-build/bin/neonateScalper -i ~/Desktop/prova_registrazione/t2_10.nii -o ~/Desktop/prova_registrazione/sct2_10.nii

terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /home/francesco/mantis/ITKStuff/Build.GLNXA64/ITK-prefix/include/ITK-5.1/itkImageSource.hxx:256:
itk::ERROR: ParabolicErodeImageFilter(0x55fa9168b8b0): With DynamicMultiThreadingOff subclass should override this method. The signature of ThreadedGenerateData() has been changed in ITK v4 to use the new ThreadIdType.
Aborted (core dumped)

Could it be a problem linked to mantis build?
Thanks and all the best,
Francesco

**Comment by richardbeare** [comment]
It looks like it is a build problem. On the positive side, there's no error about missing libraries. There have been some discussions on the forums about the threading issues with the parabolic utilities and ITK 5.1.

I am uncertain of the status at present, but you could attempt to manually bump the ITK part of mantis to a newer version. If you are using the "BumpITKVersion" branch of mantis then the version it requests if 5.1rc1. You can test different versions by modifying [this ine](https://github.com/DevelopmentalImagingMCRI/mantis/blob/0a9f9f3fea372ec7ea1c185078700c31dccce802/ITKStuff/SuperBuild/External_ITKv5.cmake#L12).

Let me know how you go. I'll check the status of that module.

**Comment by richardbeare** [comment]
Note posted: https://github.com/InsightSoftwareConsortium/ITKLabelErodeDilate/issues/27#issuecomment-623195346

**Comment by dzenanz** [comment]
The changes are not hard. [Docs](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/ITK5MigrationGuide.md#multithreading-refactored) and [example](https://github.com/InsightSoftwareConsortium/ITKTextureFeatures/commit/f794baa7546f9bb8b7d89ae3a083c9a432d55df0). Note that we have [restored progress reporting functionality](https://github.com/InsightSoftwareConsortium/ITK/pull/1575/commits/13fdc58236442f79275b3072a224e6ef6b20384f) a few months ago.

**Comment by francescomarialorusso** [comment]
Hi Richard,
thanks for your help. I tried to bumb the ITK version of the cmake file from 5.1rc1 to 5.1rc2 but the compilation fails after the installation of ITK, as follow:

Scanning dependencies of target MANTiS
[ 52%] Creating directories for 'MANTiS'
[ 58%] No download step for 'MANTiS'
[ 70%] No update step for 'MANTiS'
[ 70%] No patch step for 'MANTiS'
[ 76%] Performing configure step for 'MANTiS'
Not searching for unused variables given on the command line.
loading initial cache file /home/francesco/mantis/ITKStuff/Build.GLNXA64/MANTiS-build/CMakeCacheInit.txt
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/francesco/mantis/ITKStuff/Build.GLNXA64/MANTiS-build
[ 82%] Performing forcebuild step for 'MANTiS'
[ 88%] Performing build step for 'MANTiS'
Scanning dependencies of target segCSF
Scanning dependencies of target neonateScalper
[ 10%] Building CXX object CMakeFiles/segCSF.dir/segCSF.cxx.o
[ 20%] Building CXX object CMakeFiles/neonateScalper.dir/neonateScalper.cxx.o
In file included from /home/francesco/mantis/ITKStuff/neonateScalper.cxx:10:
/home/francesco/mantis/ITKStuff/ioutils.h:12:59: error: ‘itk::ImageIOBase::IOComponentType’ has not been declared
   12 | int readImageInfo(std::string filename, itk::ImageIOBase::IOComponentType *ComponentType, int *dim)
      |                                                           ^~~~~~~~~~~~~~~
/home/francesco/mantis/ITKStuff/ioutils.h: In function ‘int readImageInfo(std::string, int*, int*)’:
/home/francesco/mantis/ITKStuff/ioutils.h:14:113: error: ‘itk::ImageIOFactory::FileModeEnum’ has not been declared
   14 |   itk::ImageIOBase::Pointer imageIO = itk::ImageIOFactory::CreateImageIO(filename.c_str(), itk::ImageIOFactory::FileModeEnum::ReadMode);
      |                                                                                                                 ^~~~~~~~~~~~
In file included from /home/francesco/mantis/ITKStuff/neonateScalper.cxx:10:
/home/francesco/mantis/ITKStuff/ioutils.h:22:45: error: cannot convert ‘itk::ImageIOBase::IOComponentEnum’ {aka ‘itk::CommonEnums::IOComponent’} to ‘int’ in assignment
   22 |   *ComponentType = imageIO->GetComponentType();
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                             |
      |                                             itk::ImageIOBase::IOComponentEnum {aka itk::CommonEnums::IOComponent}
In file included from /home/francesco/mantis/ITKStuff/segCSF.cxx:10:
/home/francesco/mantis/ITKStuff/ioutils.h:12:59: error: ‘itk::ImageIOBase::IOComponentType’ has not been declared
   12 | int readImageInfo(std::string filename, itk::ImageIOBase::IOComponentType *ComponentType, int *dim)
      |                                                           ^~~~~~~~~~~~~~~
/home/francesco/mantis/ITKStuff/ioutils.h: In function ‘int readImageInfo(std::string, int*, int*)’:
/home/francesco/mantis/ITKStuff/ioutils.h:14:113: error: ‘itk::ImageIOFactory::FileModeEnum’ has not been declared
   14 | actory::CreateImageIO(filename.c_str(), itk::ImageIOFactory::FileModeEnum::ReadMode);
      |                                                              ^~~~~~~~~~~~

In file included from /home/francesco/mantis/ITKStuff/segCSF.cxx:10:
/home/francesco/mantis/ITKStuff/ioutils.h:22:45: error: cannot convert ‘itk::ImageIOBase::IOComponentEnum’ {aka ‘itk::CommonEnums::IOComponent’} to ‘int’ in assignment
   22 |   *ComponentType = imageIO->GetComponentType();
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                             |
      |                                             itk::ImageIOBase::IOComponentEnum {aka itk::CommonEnums::IOComponent}
/home/francesco/mantis/ITKStuff/neonateScalper.cxx: In function ‘int main(int, char**)’:
/home/francesco/mantis/ITKStuff/neonateScalper.cxx:237:21: error: ‘IOComponentType’ is not a member of ‘itk::ImageIOBase’
  237 |   itk::ImageIOBase::IOComponentType ComponentType;
      |                     ^~~~~~~~~~~~~~~
/home/francesco/mantis/ITKStuff/neonateScalper.cxx:238:43: error: ‘ComponentType’ was not declared in this scope
  238 |   if (!readImageInfo(CmdLineObj.InputIm, &ComponentType, &dim1))
      |                                           ^~~~~~~~~~~~~
/home/francesco/mantis/ITKStuff/neonateScalper.cxx:259:11: error: ‘ComponentType’ was not declared in this scope
  259 |   switch (ComponentType)
      |           ^~~~~~~~~~~~~
/home/francesco/mantis/ITKStuff/neonateScalper.cxx:261:29: error: ‘SHORT’ is not a member of ‘itk::ImageIOBase’
  261 |     case (itk::ImageIOBase::SHORT):
      |                             ^~~~~
/home/francesco/mantis/ITKStuff/neonateScalper.cxx:264:29: error: ‘USHORT’ is not a member of ‘itk::ImageIOBase’
  264 |     case (itk::ImageIOBase::USHORT):
      |                             ^~~~~~
/home/francesco/mantis/ITKStuff/neonateScalper.cxx:267:29: error: ‘INT’ is not a member of ‘itk::ImageIOBase’
  267 |     case (itk::ImageIOBase::INT):
      |                             ^~~
/home/francesco/mantis/ITKStuff/segCSF.cxx: In function ‘int main(int, char**)’:
/home/francesco/mantis/ITKStuff/segCSF.cxx:236:21: error: ‘IOComponentType’ is not a member of ‘itk::ImageIOBase’
  236 |   itk::ImageIOBase::IOComponentType ComponentType;
      |                     ^~~~~~~~~~~~~~~
/home/francesco/mantis/ITKStuff/segCSF.cxx:237:43: error: ‘ComponentType’ was not declared in this scope
  237 |   if (!readImageInfo(CmdLineObj.InputIm, &ComponentType, &dim1))
      |                                           ^~~~~~~~~~~~~
/home/francesco/mantis/ITKStuff/segCSF.cxx:259:11: error: ‘ComponentType’ was not declared in this scope
  259 |   switch (ComponentType)
      |           ^~~~~~~~~~~~~
/home/francesco/mantis/ITKStuff/segCSF.cxx:261:29: error: ‘SHORT’ is not a member of ‘itk::ImageIOBase’
  261 |     case (itk::ImageIOBase::SHORT):
      |                             ^~~~~
/home/francesco/mantis/ITKStuff/segCSF.cxx:264:29: error: ‘USHORT’ is not a member of ‘itk::ImageIOBase’
  264 |     case (itk::ImageIOBase::USHORT):
      |                             ^~~~~~
/home/francesco/mantis/ITKStuff/segCSF.cxx:267:29: error: ‘INT’ is not a member of ‘itk::ImageIOBase’
  267 |     case (itk::ImageIOBase::INT):
      |                             ^~~
make[5]: *** [CMakeFiles/segCSF.dir/build.make:83: CMakeFiles/segCSF.dir/segCSF.cxx.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:348: CMakeFiles/segCSF.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
make[5]: *** [CMakeFiles/neonateScalper.dir/build.make:83: CMakeFiles/neonateScalper.dir/neonateScalper.cxx.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:591: CMakeFiles/neonateScalper.dir/all] Error 2
make[3]: *** [Makefile:161: all] Error 2
make[2]: *** [CMakeFiles/MANTiS.dir/build.make:135: MANTiS-prefix/src/MANTiS-stamp/MANTiS-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/MANTiS.dir/all] Error 2
make: *** [Makefile:104: all] Error 2

Do you have a suggestion how to fix the issue?
All the best,
Francesco

**Comment by richardbeare** [comment]
Looks like there's some work to be done. Bumping the ITK version alone won't be enough as the threading issue in the parabolicMorphology module is only just being fixed, and a corresponding update in ITK is required.

Have to tested the branch already in mantis (late last year) called BumpITKVersion? Perhaps you are already using it. Have a play with it to see if it solves any of your problems.

**Comment by francescomarialorusso** [comment]
Yep, I'm already building mantis using the last version (the BumpITKVersion), since the previous version was not compatible with the newer version of GCC 9.2.1.
Thanks for your help!

**Comment by dzenanz** [comment]
Instead of `int ComponentType = imageIO->GetComponentType();` try `auto ComponentType = imageIO->GetComponentType();`. In ITK 5 enums are [strongly typed](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/ITK5MigrationGuide.md#strongly-typed-enumerations). Also, 5.1.0 final has been tagged and you should use that.

**Comment by richardbeare** [comment]
Hi,
I've made two sets of changes on that branch to do the following:

- pull in the corrected version of parabolicMorphology by pointing at my ITK repo on github (we'll change this later.

- Change to the new enumeration style so that things compile (under linux at least)

I haven't attempted any tests, so let me know how you go.

**Comment by francescomarialorusso** [comment]
Hi Richard,
thanks for your help. When I try to launch the "make -j2" command I receive the following error:

 /mantis/ITKStuff/Build.GLNXA64$ make -j2
Scanning dependencies of target ITK
[  5%] Creating directories for 'ITK'
[ 11%] Performing download step (git clone) for 'ITK'
fatal: repository '/home/richardb/Projects/ITK/ITK/' does not exist
fatal: repository '/home/richardb/Projects/ITK/ITK/' does not exist
fatal: repository '/home/richardb/Projects/ITK/ITK/' does not exist
-- Had to git clone more than once:
          3 times.
CMake Error at ITK-prefix/tmp/ITK-gitclone.cmake:31 (message):
  Failed to clone repository: '/home/richardb/Projects/ITK/ITK/'


make[2]: *** [CMakeFiles/ITK.dir/build.make:111: ITK-prefix/src/ITK-stamp/ITK-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:98: CMakeFiles/ITK.dir/all] Error 2
make: *** [Makefile:104: all] Error 2

Seems that it is not able to find a specific folder. Do you know a fix for that? 
Thanks a lot
Francesco

**Comment by richardbeare** [comment]
Many apologies - I stupidly forgot to switch something back.

I am working on fixing this up today, so you should have something to work with in a few hours.

**Comment by richardbeare** [comment]
@francescomarialorusso 
I have something now that I hope is testable. It is in the BumpITKVersion branch, as before. I have done a force push to hide some stupid errors, which may make the pull look different at your end.

The ITK repo in mantis is now pointing at my version on github, rather than the InsightConsortium version, as we haven't yet moved the module update into ITK. Also I've modified the way in which matlab calls the executables, as I was getting problems with shared libraries. Hopefully this doesn't mess you up. With a bit of luck it will fix the errors you were getting in the first message in this issue thread.

**Comment by francescomarialorusso** [comment]
Hi Richard,
I tried the scalper and now it compile and works just fine!
Thanks a lot for your help I really appreciated!

**Comment by richardbeare** [comment]
Excellent. Let me know if you see any further threading issues. I will merge the branch once ITK is referencing the correct parabolicMorphology version.
