### ISSUE TITLE
No bin folder in MANTiS-build

### ISSUE THREAD

**Issue by anurudhya** [DevelopmentalImagingMCRI/mantis#13]
Hi,
I tried installing Mantis in Mac and everything went well without any error. However, I do not find the bin folder and its content such as segCSF. Because of this watershed segmentation, morphological segmentation and the other jobs are failing. I am using Mac. It would be really great if somebody could help me fixing this issue.

Thank you in advance.

Regards,
Anu

**Comment by anurudhya** [comment]
Hi, 
I just tried make -j2 command again to see if I could generate the executables. But it ended up with the following error messages.

[  5%] Creating directories for 'ITK'
make[2]: *** No rule to make target `ITK-prefix/src/ITK-stamp/ITK-gitinfo.txt', needed by `ITK-prefix/src/ITK-stamp/ITK-download'.  Stop.
make[1]: *** [CMakeFiles/ITK.dir/all] Error 2
make: *** [all] Error 2

Thank you in advance.

Regards,
Anu

**Comment by richardbeare** [comment]
Do you have the developer tools installed on the mac? It appears to be failing at the stage where it attempts to download dependencies. To test, start a terminal and run "git". If it isn't installed you will probably be prompted by a command that will install developer tools for you.

The build usually takes quite a long time. Something hasn't worked properly if finishes very quickly.

**Comment by richardbeare** [comment]
Hi,
I've been lazy in merging my updates, hoping for more widespread testing. The likely problem is the master version attempting to fetch ITK from the original repo, while it now resides at github.

Try deleting the cloned folder. Reclone, then do
```
cd mantis
git checkout BumpITKVersion
```
then follow the other instructions.

If you report success I will merge the changes into the master branch.
Thanks for the report.

**Comment by anurudhya** [comment]
Hi,
Thank you for the reply. I tried git in the terminal and it works. 
I also deleted the cloned folder and recloned it again by 

`git clone https://github.com/DevelopmentalImagingMCRI/mantis.git`
and then
`cd mantis`
`git checkout BumpITKVersion`
`git submodule init`
`git submodule update`

However, it fails when I execute the last line `git submodule update` and the error message is as follows:
fatal: unable to connect to git.code.sf.net:
git.code.sf.net[0: 216.105.38.16]: errno=Connection refused

fatal: clone of 'git://git.code.sf.net/p/tclap/code' into submodule path '/Users/xxxx/mantis/ITKStuff/tclap-code' failed
Failed to clone 'ITKStuff/tclap-code'. Retry scheduled
Cloning into '/Users/xxxx/mantis/ITKStuff/tclap-code'...
fatal: unable to connect to git.code.sf.net:
git.code.sf.net[0: 216.105.38.16]: errno=Connection refused

fatal: clone of 'git://git.code.sf.net/p/tclap/code' into submodule path '/Users/xxxx/mantis/ITKStuff/tclap-code' failed
Failed to clone 'ITKStuff/tclap-code' a second time, aborting.

Am I doing something wrong here. Thank you in advance.

Regards,
Anu

**Comment by anurudhya** [comment]
Hi,
After I did what you have suggested in your answer, it worked fine. The problem that I had mentioned before was because of the network and I tried while connected to another network and it worked fine now.

Thank you very much.

Regards,
Anu
