### ISSUE TITLE
Parse error: watershed segmentation

### ISSUE THREAD

**Issue by anurudhya** [DevelopmentalImagingMCRI/mantis#14]
Hi,
I have given 3D reconstructed image as input to the tool and the job runs fine until last 'Move/Delete Files' and it fails in the watershed segmentation of CSF with the exact error shown below:

PARSE ERROR: Argument: scans/superresolution_masked_brain_0.7_tr.nii
             Couldn't find match for argument

Brief USAGE: 
   /Users/anurudhya/spm12/toolbox/mantis/ITKStuff/Build.MACI64/MANTiS-build
                                        /bin/segCSF  [-d] [--prefix
                                        <string>] --csf <string> --grey
                                        <string> --outputprefix <string> -i
                                        <string> [--] [--version] [-h]

For complete USAGE and HELP type: 
   /Users/anurudhya/spm12/toolbox/mantis/ITKStuff/Build.MACI64/MANTiS-build/bin/segCSF --help

12-Feb-2021 12:31:09 - Failed  'Watershed segmentation of CSF'

And the subsequent steps fail because of the file being missing due to failed previous step.

Can someone help me on how to debug this problem or suggest a fix for this. Thank you in advance.

Regards,
Anu

**Comment by richardbeare** [comment]
Hi,
Spaces in filenames and paths are a common problem. Is it possible that you have a path "something scans/superresolution_masked_brain_0.7_tr.nii", with a space before the "scans" part of the name? If so, please rerun with a modified path (e.g. underscores, _ instead of spaces).
