### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by parinazbabaee** [DevelopmentalImagingMCRI/mantis#17]
Hi ,

I have problem with performing the following part in the Terminal in MacOS:

## Make a build directory with the matlab architecture in the name

export ARCH=$(echo "disp(sprintf('\n%s', computer)),quit" | matlab -nojvm -nodesktop -nosplash |tail -1)

Here is the error that I get:

 disp(sprintf('
              |
Error: Character vector is not terminated properly.
 
So I changed it to:

export ARCH=$(echo "disp(sprintf('\n%s', computer)),quit") | matlab -nojvm -nodesktop -nosplash |tail -1

but when I use:

cmake ../SuperBuild

I get the following error and "make -j2" can not generate and install anyting.

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3967 (add_custom_target):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  External_ITKv5.cmake:21 (ExternalProject_Add)
  SuperBuild.cmake:214 (include)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4141 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  External_ITKv5.cmake:21 (ExternalProject_Add)
  SuperBuild.cmake:214 (include)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2630 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4166 (_ep_add_mkdir_command)
  External_ITKv5.cmake:21 (ExternalProject_Add)
  SuperBuild.cmake:214 (include)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3161:EVAL:2 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3161 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4167 (_ep_add_download_command)
  External_ITKv5.cmake:21 (ExternalProject_Add)
  SuperBuild.cmake:214 (include)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3396:EVAL:2 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3396 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4168 (_ep_add_update_command)
  External_ITKv5.cmake:21 (ExternalProject_Add)
  SuperBuild.cmake:214 (include)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3456:EVAL:2 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3456 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4169 (_ep_add_patch_command)
  External_ITKv5.cmake:21 (ExternalProject_Add)
  SuperBuild.cmake:214 (include)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3699:EVAL:2 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3699 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4170 (_ep_add_configure_command)
  External_ITKv5.cmake:21 (ExternalProject_Add)
  SuperBuild.cmake:214 (include)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3779:EVAL:2 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3779 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4171 (_ep_add_build_command)
  External_ITKv5.cmake:21 (ExternalProject_Add)
  SuperBuild.cmake:214 (include)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3836:EVAL:2 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3836 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4172 (_ep_add_install_command)
  External_ITKv5.cmake:21 (ExternalProject_Add)
  SuperBuild.cmake:214 (include)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3967 (add_custom_target):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  SuperBuild.cmake:236 (ExternalProject_Add)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4141 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  SuperBuild.cmake:236 (ExternalProject_Add)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2630 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4166 (_ep_add_mkdir_command)
  SuperBuild.cmake:236 (ExternalProject_Add)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3161:EVAL:2 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3161 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4167 (_ep_add_download_command)
  SuperBuild.cmake:236 (ExternalProject_Add)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3396:EVAL:2 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3396 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4168 (_ep_add_update_command)
  SuperBuild.cmake:236 (ExternalProject_Add)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3456:EVAL:2 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3456 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4169 (_ep_add_patch_command)
  SuperBuild.cmake:236 (ExternalProject_Add)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3699:EVAL:2 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3699 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4170 (_ep_add_configure_command)
  SuperBuild.cmake:236 (ExternalProject_Add)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3779:EVAL:2 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3779 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4171 (_ep_add_build_command)
  SuperBuild.cmake:236 (ExternalProject_Add)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3836:EVAL:2 (ExternalProject_Add_Step)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3836 (cmake_language)
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:4172 (_ep_add_install_command)
  SuperBuild.cmake:236 (ExternalProject_Add)
  CMakeLists.txt:26 (include)

CMake Error at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471:EVAL:2 (add_custom_command):
  OUTPUT containing a ">" is not allowed.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:2471 (cmake_language)
  SuperBuild.cmake:260 (ExternalProject_Add_Step)
  CMakeLists.txt:26 (include)

Would you please help me to resolve this.

Parinaz.

**Comment by richardbeare** [comment]
I'm not sure what has gone wrong with the command - I pasted what you have written into a linux terminal and it worked. What shell are you using - perhaps this is a bash/zsh difference?

The aim is to set the ARCH environment variable, which you can do manually, as follows:

- start matlab
- run the computer command. i.e type 'computer', without quotes, into the matlab terminal. It should print something like GLNXA64 (under linux). You will get something different on the mac, probably MACsomething.
- exit matlab
- type 'export ARCH=GLNXA64' (without quotes) into the shell where you will run cmake, and 

Note that we haven't tested this with new M1 macs. We might require an update to support them

Let me know how you go

**Comment by parinazbabaee** [comment]
Hi,

Thank you very much for your kind reply. I resolved the problem as you said and now I am having issue with running "make -j2". following is the error that I get:

[  5%] Creating directories for 'ITK'
[ 11%] Performing download step (git clone) for 'ITK'
Cloning into 'ITK'...
fatal: reference is not a tree: 89581d46a00d680e5544c870f4328a1a5d64e798
CMake Error at ITK-prefix/tmp/ITK-gitclone.cmake:49 (message):
  Failed to checkout tag: '89581d46a00d680e5544c870f4328a1a5d64e798'


make[2]: *** [ITK-prefix/src/ITK-stamp/ITK-download] Error 1
make[1]: *** [CMakeFiles/ITK.dir/all] Error 2
make: *** [all] Error 2
 
I would greatly appreciate your help.
Parinaz.

**Comment by richardbeare** [comment]
Apologies for this. I suspect this has to do with my reorganising my clone of the ITK code. I'll attempt to fix over the next day or two, and bump the versions.

**Comment by parinazbabaee** [comment]
Thank you very much for your quick reply. I appreciate your help and I will wait to hear from you.

Thank you,
Parinaz.

**Comment by richardbeare** [comment]
Hi,
I've made some updates - please test as follows and let me know how you go:

First - update your copy of mantis code:

```bash
cd YourMantisFolder.  # change as required
git fetch --all
git checkout Bump
```
Remove all the old build - e.g 

```bash
cd ITKStuff/
rm -rf Build.MYARCH. # change as required
mkdir Build.MYARCH
```

Then repeat the original build instructions

**Comment by parinazbabaee** [comment]
Thank you very much, I appreciate your help. it worked very well.
