### ISSUE TITLE
Run Mantis from Windows 10

### ISSUE THREAD

**Issue by valeriaelisacontarino** [DevelopmentalImagingMCRI/mantis#2]
Dear all,

I'm working on a Windows 10 system and I would like to know if there's an easy way to use Mantis from MATLAB+SPM on Windows. The reason is that I believe I cannot install MATLAB from linux bash and I would avoid to use VM.

What I did is compile Mantis from Linux bash and convert the mantis/.../bin files with x86_64-w64-mingw32-gcc command.
I'm able to start Mantis toolbox from SPM on Windows and perform Phase 1 BUT I guess it gives error as it tries to recall the mantis bin files (it does not create ..._csfmask.nii).

Do u kindly have any suggestion?
Thanks,

Valeria

**Comment by valeriaelisacontarino** [comment]
------------------------------------------------------------------------
Running job #1
------------------------------------------------------------------------
Running 'Named File Selector'
Done    'Named File Selector'
Running 'Folders for phases - image files get placed here'
Done    'Folders for phases - image files get placed here'
Running 'Path for all components of the neonate template'
Done    'Path for all components of the neonate template'
Running 'Mantis: Phase 1 tissue classification'

SPM12: spm_preproc_run (v6365)                     19:17:28 - 03/10/2017
========================================================================
Segment D:\Neonati_Vol\NOUR_prove_su_T2\T2ax_brain.nii
Completed                               :          19:19:04 - 03/10/2017
Done    'Mantis: Phase 1 tissue classification'
Running 'Move/Delete Files'
Done    'Move/Delete Files'
Running 'Move/Delete Files'
Done    'Move/Delete Files'
Running 'Move/Delete Files'
Done    'Move/Delete Files'
Running 'Move/Delete Files'
Done    'Move/Delete Files'
Running 'Move/Delete Files'
Done    'Move/Delete Files'
Running 'Move/Delete Files'
Done    'Move/Delete Files'
Running 'Watershed segmentation of CSF'
**Impossibile trovare il percorso specificato.**

**Comment by valeriaelisacontarino** [comment]
![mantis_error](https://user-images.githubusercontent.com/30657262/31139057-af463bea-a870-11e7-9cd8-145fb2564fe9.png)

**Comment by richardbeare** [comment]
Well done - it sounds like you made a lot of progress.

I presume the error is coming from matlab not being able to find the ITK executables. This may be because they end in .exe under windows. I'll have a play around today and see if I can put in some windows support for you to test.

**Comment by valeriaelisacontarino** [comment]
Thanks Richard, hope in your kind suggestion

**Comment by valeriaelisacontarino** [comment]
your silence scares me... no hope?

**Comment by richardbeare** [comment]
Some hope - just been busy.

I have to get a windows build working, which I hope is the part that will
take the most time. I'm nearly there, I think.

**Comment by richardbeare** [comment]
Good news. I've been able to run an example on windows with no changes to the matlab code. I'll put some instructions on building up on the web page tonight. I've built using the MSYS2 framework. However, if you've got exe files that you are confident will actually run under windows, then all you need to do is create the following path and put the exe files in it:

```bash
spm/toolbox/mantis/ITKStuff/Build.PCWIN64/MANTiS-build/bin/
```
All of that is default, apart from the `PCWIN64` part. That suffix may have been a bad design idea, but was intended to support multiple platforms in the same folders. It needs to correspond to the result of the matlab command

```matlab
computer
```

**Comment by richardbeare** [comment]
I've added some windows installation instructions at the bottom of our [installation page](http://developmentalimagingmcri.github.io/mantis/installation/).

No changes to the code. See if they make sense and work for you.
