### ISSUE TITLE
MANTiS Watershed segmentation of CSF issue 

### ISSUE THREAD

**Issue by aurorazi** [DevelopmentalImagingMCRI/mantis#20]
Hi, I'm trying to use the MANTiS tool. But I am having issue with the Watershed segmentation of CSF. I am putting the code generated below:

04-Oct-2023 15:56:57 - Running 'Watershed segmentation of CSF'
/bin/bash: line 1: /home/aurora/Downloads/spm12/toolbox/mantis/ITKStuff/Build.GLNXA64/MANTiS-build/bin/segCSF: No such file or directory
04-Oct-2023 15:56:58 - Failed  'Watershed segmentation of CSF'
Error using read_hdr
Error reading header file "/home/aurora/Downloads/neonates_nifti/mini_034/Phase2/mini_034_T1W_3D_FFE_20220222131319_csfmask.nii".
In file "/home/aurora/Downloads/spm12/@nifti/private/read_hdr.m" (v7504), function "read_hdr" at line 39.
In file "/home/aurora/Downloads/spm12/@nifti/nifti.m" (v7758), function "nifti" at line 26.
In file "/home/aurora/Downloads/spm12/spm_get_space.m" (v6379), function "spm_get_space" at line 18.
In file "/home/aurora/Downloads/spm12/toolbox/mantis/mantisCopyHeader.m" (???), function "mantisCopyHeader" at line 5.
In file "/home/aurora/Downloads/spm12/toolbox/mantis/cg_mantis_ws_csf_run.m" (???), function "cg_mantis_ws_csf_run" at line 34.

04-Oct-2023 15:56:58 - Running 'Morphogical clean up of White matter'
/bin/bash: line 1: /home/aurora/Downloads/spm12/toolbox/mantis/ITKStuff/Build.GLNXA64/MANTiS-build/bin/cleanWM: No such file or directory
04-Oct-2023 15:56:58 - Failed  'Morphogical clean up of White matter'
Error using read_hdr
Error reading header file "/home/aurora/Downloads/neonates_nifti/mini_034/Phase2/mini_034_T1W_3D_FFE_20220222131319_csfmask.nii".
In file "/home/aurora/Downloads/spm12/@nifti/private/read_hdr.m" (v7504), function "read_hdr" at line 39.
In file "/home/aurora/Downloads/spm12/@nifti/nifti.m" (v7758), function "nifti" at line 26.
In file "/home/aurora/Downloads/spm12/spm_get_space.m" (v6379), function "spm_get_space" at line 18.
In file "/home/aurora/Downloads/spm12/toolbox/mantis/mantisCopyHeader.m" (???), function "mantisCopyHeader" at line 4.
In file "/home/aurora/Downloads/spm12/toolbox/mantis/cg_mantis_wm_clean_run.m" (???), function "cg_mantis_wm_clean_run" at line 32.

04-Oct-2023 15:56:58 - Running 'Path for all components of the neonate firstnorm'
04-Oct-2023 15:56:58 - Done    'Path for all components of the neonate firstnorm'
04-Oct-2023 15:56:58 - Running 'Template deformations'
04-Oct-2023 15:57:13 - Done    'Template deformations'
04-Oct-2023 15:57:13 - Running 'Make subject specific template'
04-Oct-2023 15:57:17 - Failed  'Make subject specific template'
Error using spm_vol>spm_vol_hdr
File "/home/aurora/Downloads/neonates_nifti/mini_034/Phase2/mini_034_T1W_3D_FFE_20220222131319_csfmask.nii" does not exist.
In file "/home/aurora/Downloads/spm12/spm_vol.m" (v5958), function "spm_vol_hdr" at line 80.
In file "/home/aurora/Downloads/spm12/spm_vol.m" (v5958), function "spm_vol" at line 61.
In file "/home/aurora/Downloads/spm12/toolbox/mantis/cg_mantis_make_tpm_run.m" (???), function "cg_mantis_make_tpm_run" at line 50.

No executable modules, but still unresolved dependencies or incomplete module inputs.
The following modules did not run:
Failed: Watershed segmentation of CSF
Failed: Morphogical clean up of White matter
Failed: Make subject specific template
Skipped: Final spm segmentation
Skipped: Hard segmentation of phase 1
Skipped: Hard segmentation of phase 2

I tried to look at the issues other people had but I do not seems to be able to solve the problem in the same way.

Thanks

**Comment by richardbeare** [comment]
Hi,
Thanks for your interest in mantis.
This looks like the result of a build problem. Can you verify the following:

does the following folder exist?
```bash

/home/aurora/Downloads/spm12/toolbox/mantis/ITKStuff/Build.GLNXA64/MANTiS-build/

```

if so, what is the content of

```bash

/home/aurora/Downloads/spm12/toolbox/mantis/ITKStuff/Build.GLNXA64/MANTiS-build/bin

```
If there's nothing in the bin folder then the build step has either been skipped or failed. Instructions are [here](https://developmentalimagingmcri.github.io/mantis/installation/) under "Build ITK components"

It is a while since we've updated the code so it is possible that there will be problems on newer systems. Please post errors that occur as you work through these steps. Note that the build requires your local copy of mantis to have been made using a `git clone` process, not by downloading the github zip file.

**Comment by aurorazi** [comment]
Thanks for your help. 
I had to follow the steps a couple of time but it seems to be working now. The problem is that for some of the fileI upload matlab is killed whit no comment. 
I don't know if is a format problem or once again a build problem.

**Comment by richardbeare** [comment]
Any build problem will tend to result in some or all of the files missing from `ITKStuff/Build.GLNXA64/MANTiS-build/bin` . Can you list that folder (note that it might be Build.SomethingElse if you're not running on linux)?

**Comment by aurorazi** [comment]
The folder contains:
cleanWM
compareMasks
compareMasksSurf
neonateScalper
segCSF


Il giorno mar 10 ott 2023 alle ore 22:33 Richard Beare <
***@***.***> ha scritto:

**Comment by richardbeare** [comment]
That looks complete. Can you track down a specific problem file?

**Comment by aurorazi** [comment]
I am attaching some of the file that are problematic for me
 file.zip
<https://drive.google.com/file/d/11Hobhu5_EuYWnjvlWD5VfL6VvbIUSk6l/view?usp=drive_web>

Il giorno mer 11 ott 2023 alle ore 11:48 Richard Beare <
***@***.***> ha scritto:

**Comment by richardbeare** [comment]
I've had a quick look at a couple of these - I don't expect mantis will work on all of them - it is designed for traditional T2 scans with bright CSF, and one of the problem cases isn't like that.

It is worth checking the origin setting for each scan. The one I looked at was far from the typical position and may have been the cause of the problem. You can use the SPM Display tool to reset the origin to something more standard, which may fix the issues.

**Comment by aurorazi** [comment]
Thanks I will check and report back to you as soon as possible.


Il giorno mer 11 ott 2023 alle ore 14:16 Richard Beare <
***@***.***> ha scritto:

**Comment by aurorazi** [comment]
Here I am with the report, so I changed the origin setting for each scan
and some of them are still giving the same issue, but for the scan
"mini_004_T2W_TSE_20211130111238a.nii" everything seems to have worked.

Now to be sure that everything worked properly I'm listing the files that
are in the 'Phase 1' and 'Phase 2' folder.
Phase 1: "c1mini_004_T2W_TSE_20211130111238a.nii"
"c2mini_004_T2W_TSE_20211130111238a.nii"
"c3mini_004_T2W_TSE_20211130111238a.nii"
"c4mini_004_T2W_TSE_20211130111238a.nii"
"c5mini_004_T2W_TSE_20211130111238a.nii"
"c6mini_004_T2W_TSE_20211130111238a.nii"
"c7mini_004_T2W_TSE_20211130111238a.nii"
"c8mini_004_T2W_TSE_20211130111238a.nii"
"c9mini_004_T2W_TSE_20211130111238a.nii"
"h1mini_004_T2W_TSE_20211130111238a.nii"
"h2mini_004_T2W_TSE_20211130111238a.nii"
"h3mini_004_T2W_TSE_20211130111238a.nii"
"iy_mini_004_T2W_TSE_20211130111238a.nii"
"mini_004_T2W_TSE_20211130111238a_seg8.nii"
"y_mini_004_T2W_TSE_20211130111238a.nii"
Phase 2: "atlas_mini_004_T2W_TSE_20211130111238a.nii"
"c1mini_004_T2W_TSE_20211130111238a.nii"
"c2mini_004_T2W_TSE_20211130111238a.nii"
"c3mini_004_T2W_TSE_20211130111238a.nii"
"c4mini_004_T2W_TSE_20211130111238a.nii"
"c5mini_004_T2W_TSE_20211130111238a.nii"
"c6mini_004_T2W_TSE_20211130111238a.nii"
"c7mini_004_T2W_TSE_20211130111238a.nii"
"c8mini_004_T2W_TSE_20211130111238a.nii"
"c9mini_004_T2W_TSE_20211130111238a.nii"
"hardmini_004_T2W_TSE_20211130111238a.nii"
"iy_mini_004_T2W_TSE_20211130111238a.nii"
"mini_004_T2W_TSE_20211130111238a.nii"
"mini_004_T2W_TSE_20211130111238a_csfmask.nii"
"mini_004_T2W_TSE_20211130111238a_seg8.nii"
"norm_atlas_mini_004_T2W_TSE_20211130111238a.nii"
"y_mini_004_T2W_TSE_20211130111238a.nii"
Are those all the file that should be in the folder?

Il giorno mer 11 ott 2023 alle ore 14:39 Aurora Orazi <
***@***.***> ha scritto:

**Comment by richardbeare** [comment]
I don't expect mini_004_T2W_FFE_20211130111238.nii to work - not a standard T2. I got the others to work.

That is the complete output. FYI - the two phase approach was designed to deal with large ventricles and hyperintense white matter common in premature babies. The examples you have don't show this sort of structure. If all your participants are like the problem cases then you may be happy with the Phase1 results.

**Comment by aurorazi** [comment]
Hi,

Thanks to your support I have successfully initialized all the files I
needed.
However I am finding some difficulties in visualizing the volume with the
segmented parts.
I have not found lots of things online on how to do it, so I  was asking if
you could suggest some optimal function to do so.

Hoping to hear from you soon
Aurora

Il giorno mer 11 ott 2023 alle ore 23:10 Richard Beare <
***@***.***> ha scritto:

**Comment by richardbeare** [comment]
If you mean viewing the various segmentation images (e.g. c1mini_004_T2W_TSE_20211130111238a) or the combined hard segmentation (hardmini_004_T2W_TSE_20211130111238a.nii), I tend to use one of the non-spm visualisation tools that support colour overlays. They all do things slightly differently and are good for different purposes. fsleyes from the fsl tool suite will view multiple multiple images and allow label colourmaps to be applied to images like the hard segmentation. You can switch layers on and off easily, which is good for checking boundaries. Other options include freeview, from freesurfer and mrview from the mrtrix suite.
