### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by annayoungkin1** [DevelopmentalImagingMCRI/mantis#21]
Hello,
Whenever I try to run the mantis segmentation pipeline I run into the same issue during CSF segmentation: PARSE ERROR: Argument: [scalped T2 file path name]
             Couldn't find match for argument
do you have any idea how I can fix this? all previous steps of the pipeline work fine.
Thank you.

**Comment by richardbeare** [comment]
Can you post a screenshot? I'm trying to figure out whether the error is from the ITK tools or parts of matlab.

**Comment by annayoungkin1** [comment]
<img width="980" alt="Screenshot 2024-03-05 at 9 15 41 PM" src="https://github.com/DevelopmentalImagingMCRI/mantis/assets/162389183/4469115c-38b3-445b-9013-f13e2f680dba">

**Comment by annayoungkin1** [comment]
I already tried deleting and re-downloading mantis but have the same issue

**Comment by richardbeare** [comment]
Odd - can only guess there must have been a typo in a commit somewhere. I'll check it out.

**Comment by annayoungkin1** [comment]
Ok thank you!

**Comment by richardbeare** [comment]
I just realised what the problem is - spaces in the "TOSHIBA EXT" part of the filename.
Escaping system calls correctly is a bit of a mess and this is something we've never fixed.

**Comment by annayoungkin1** [comment]
Ok, so perhaps I need to take the files off of my external drive and try in another place. I’ll give it a go. Thanks!

**Comment by richardbeare** [comment]
You can change the drive label - stick in an underscore instead of a space

**Comment by annayoungkin1** [comment]
It is working now. thank you so much
