### ISSUE TITLE
Fitting images to template

### ISSUE THREAD

**Issue by annayoungkin1** [DevelopmentalImagingMCRI/mantis#22]
Hello! I have one more question. For some reason, my skull stripped images are much larger than the mantis template (image attached with the mantis template overlayed). I am running these through the NEOrs pipeline, so the registration of the images is done for me using a template from WashU. Do you know of a way to easily match my image sizes to the template?
Thank you!
[
<img width="409" alt="Screenshot 2024-03-14 at 1 18 28 PM" src="https://github.com/DevelopmentalImagingMCRI/mantis/assets/162389183/e85821c3-e35a-4a5a-b4b7-a387497c09b3">
](url)

**Comment by richardbeare** [comment]
These are much bigger than the mantis template - presumably much older? I'd be surprised if default spm registration settings (which is what mantis uses) would work. It it likely to be important to include an initial guess as to the necessary scaling. It think there is some way of doing this hidden away in spm, but I don't remember details. Using it from mantis may will require modifications to the pipeline.

**Comment by annayoungkin1** [comment]
Figured this out by re-registering the original images to a 32 bit template instead of 64 prior to skull stripping.
