### ISSUE TITLE
Brain volumes - output from seg8.mat or hard segmentation .nii file?

### ISSUE THREAD

**Issue by taniarfv** [DevelopmentalImagingMCRI/mantis#23]
Hi, 
I'm using the MANTiS toolbox to obtain the brain tissue volumes through the seg8.mat file. Then I used another toolbox (ITK-SNAP) for looking into the original image overlapped with the combined hard segmentation nifti file. However, I noticed the volumes are different from the ones provided from the seg8.mat file.
What output file should be considered to obtain the brain volume?
Thank you in advance!
Tânia

**Comment by richardbeare** [comment]
IIRC the volumes in seg8.mat are derived from the probability maps - essentially adding up the voxel probabilities and using the diagonal of the transform to define voxel volume, where as the volume from itksnap and the hard segmentation is simply a count of voxels surviving a thresholding step. You may argue that the seg8 approach is performing some partial volume correction, but the difference tends to be very small. It usually doesn't matter which you use, as long as you use the same choice throughout the analysis.

**Comment by taniarfv** [comment]
Thank you for answering! 
You are right, the difference tends to be small - the biggest difference between them are ~13 mL for the GM and CSF.
I will select one and use the same throughout the analysis.
