### ISSUE TITLE
"Dunno about this gcc"

### ISSUE THREAD

**Issue by francescomarialorusso** [DevelopmentalImagingMCRI/mantis#8]
Hi,
I have some troubles compiling Mantis on Ubuntu 19.10 with GCC [gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008] and Cmake 3.13.4.
The building process fails at early stage with this errors:

Scanning dependencies of target itkvcl
[  0%] Building CXX object Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/vcl_deprecated.cxx.o
In file included from /home/francesco/mantis/ITKStuff/Build.GLNXA64/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_iostream.h:5,
                 from /home/francesco/mantis/ITKStuff/Build.GLNXA64/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_deprecated.cxx:4:
/home/francesco/mantis/ITKStuff/Build.GLNXA64/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_compiler.h:90:4: error: #error "Dunno about this gcc"
   90 | #  error "Dunno about this gcc"
      |    ^~~~~
[  0%] Building CXX object Modules/ThirdParty/KWSys/src/KWSys/CMakeFiles/itksys.dir/DynamicLoader.cxx.o
make[5]: *** [Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/build.make:63: Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/vcl_deprecated.cxx.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:635: Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[  0%] Building CXX object Modules/ThirdParty/KWSys/src/KWSys/CMakeFiles/itksys.dir/EncodingCXX.cxx.o
[  0%] Building CXX object Modules/ThirdParty/KWSys/src/KWSys/CMakeFiles/itksys.dir/Glob.cxx.o
[  0%] Building CXX object Modules/ThirdParty/KWSys/src/KWSys/CMakeFiles/itksys.dir/RegularExpression.cxx.o
[  0%] Building CXX object Modules/ThirdParty/KWSys/src/KWSys/CMakeFiles/itksys.dir/SystemTools.cxx.o
[  0%] Building CXX object Modules/ThirdParty/KWSys/src/KWSys/CMakeFiles/itksys.dir/CommandLineArguments.cxx.o
[  0%] Building CXX object Modules/ThirdParty/KWSys/src/KWSys/CMakeFiles/itksys.dir/FStream.cxx.o
[  0%] Building CXX object Modules/ThirdParty/KWSys/src/KWSys/CMakeFiles/itksys.dir/SystemInformation.cxx.o
[  0%] Linking CXX static library ../../../../../lib/libitksys-4.12.a
[  0%] Built target itksys
make[3]: *** [Makefile:152: all] Error 2
make[2]: *** [CMakeFiles/ITK.dir/build.make:112: ITK-prefix/src/ITK-stamp/ITK-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/ITK.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Is there anything I can do to make the compilation works?
Please let me know if you need more details,
Best regards
Francesco

**Comment by richardbeare** [comment]
We almost certainly need to bump the version of ITK to a more recent one. I will look into it.

If you want to have a play around, look at 
https://github.com/DevelopmentalImagingMCRI/mantis/blob/26da7cde14fb86979b187f212dfbe9b4a236112b/ITKStuff/SuperBuild/External_ITKv4.cmake#L11

and select a more recent tag

**Comment by richardbeare** [comment]
@francescomarialorusso 
I've made a branch available for testing that uses ITK 5.1. Please have a try and let me know how you go.
``` bash
git clone https://github.com/DevelopmentalImagingMCRI/mantis.git
cd mantis
git checkout BumpITKVersion
git submodule init
git submodule update
```

Then proceed as before.

**Comment by francescomarialorusso** [comment]
Hi Richard,
I tried the instruction you posted and installation process worked fine! I still need to test it with some data. I'll keep you posted as soon as I have the results. Thanks a lot for your help!
Best regards
Francesco

**Comment by richardbeare** [comment]
Great. Thanks for letting me know.
