### ISSUE TITLE
ninja error on Windows7

### ISSUE THREAD

**Issue by jdr1991** [DevelopmentalImagingMCRI/mantis#9]
Hi,

I am trying to install MANTiS on a Windows 7 64-bit system, I followed the "Preliminary windows instructions" on the "Installation" page, however, I got these errors in the "ninja" step:

Administrator@Dengrong-PC MSYS /d/mantis/ITKStuff/Build.PCWIN64
ninja
[1/17] Creating directories for 'ITK'
[2/17] Performing download step (git clone) for 'ITK'
-- Avoiding repeated git clone, stamp file is up to date: 'D:/mantis/ITKStuff/Build.PCWIN64/ITK-prefix/src/ITK-stamp/ITK-gitclone-lastrun.txt'
[3/17] No patch step for 'ITK'
[4/17] No update step for 'ITK'
[5/17] Performing configure step for 'ITK'
Not searching for unused variables given on the command line.
loading initial cache file D:/mantis/ITKStuff/Build.PCWIN64/ITK-build/CMakeCacheInit.txt
CMake Warning at CMake/ITKModuleEnablement.cmake:86 (message):
  ITK_BUILD_ALL_MODULES is deprecated, please remove this entry from the
  CMake cache (edit the CMakeCache.txt file located in the top level of the
  ITK build tree directly or via the CMake GUI), and use
  ITK_BUILD_DEFAULT_MODULES instead.
Call Stack (most recent call first):
  CMakeLists.txt:337 (include)

-- Enabled ITKAnisotropicSmoothing, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKAntiAlias, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKBiasCorrection, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKBinaryMathematicalMorphology, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKBioCell, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKClassifiers, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKColormap, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKCommon, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKConnectedComponents, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKConvolution, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKCurvatureFlow, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKDICOMParser, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKDeconvolution, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKDeformableMesh, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKDenoising, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKDiffusionTensorImage, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKDisplacementField, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKDistanceMap, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKDoubleConversion, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKEigen, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKExpat, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKFEM, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKFEMRegistration, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKFFT, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKFastMarching, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKFiniteDifference, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKGDCM, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKGIFTI, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKGPUAnisotropicSmoothing, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKGPUCommon, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKGPUFiniteDifference, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKGPUImageFilterBase, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKGPUPDEDeformableRegistration, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKGPURegistrationCommon, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKGPUSmoothing, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKGPUThresholding, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKHDF5, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOBMP, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOBioRad, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOCSV, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOGDCM, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOGE, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOGIPL, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOHDF5, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOIPL, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOImageBase, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOJPEG, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOLSM, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOMRC, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOMesh, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOMeta, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIONIFTI, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIONRRD, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOPNG, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIORAW, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOSiemens, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOSpatialObjects, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOStimulate, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOTIFF, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOTransformBase, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOTransformHDF5, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOTransformInsightLegacy, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOTransformMatlab, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOVTK, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIOXML, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageAdaptors, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageCompare, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageCompose, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageFeature, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageFilterBase, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageFunction, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageFusion, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageGradient, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageGrid, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageIntensity, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageLabel, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageNoise, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageSources, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKImageStatistics, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKIntegratedTest, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKJPEG, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKKLMRegionGrowing, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKKWIML, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKKWSys, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKLabelMap, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKLabelVoting, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKLevelSets, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKLevelSetsv4, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKMarkovRandomFieldsClassifiers, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKMathematicalMorphology, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKMesh, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKMetaIO, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKMetricsv4, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKNIFTI, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKNarrowBand, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKNetlib, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKNeuralNetworks, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKNrrdIO, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKOpenJPEG, needed by [ITKReview].
-- Enabled ITKOptimizers, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKOptimizersv4, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKPDEDeformableRegistration, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKPNG, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKPath, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKPolynomials, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKQuadEdgeMesh, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKQuadEdgeMeshFiltering, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKRegionGrowing, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKRegistrationCommon, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKRegistrationMethodsv4, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKReview, requested by Module_ITKReview.
-- Enabled ITKSignedDistanceFunction, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKSmoothing, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKSpatialFunction, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKSpatialObjects, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKStatistics, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKTIFF, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKTestKernel, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKThresholding, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKTransform, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKTransformFactory, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKVNL, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKVNLInstantiation, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKVTK, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKVideoCore, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKVideoFiltering, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKVideoIO, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKVoronoi, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKWatersheds, requested by ITK_BUILD_DEFAULT_MODULES.
-- Enabled ITKZLIB, requested by ITK_BUILD_DEFAULT_MODULES.
CMake Deprecation Warning at Modules/ThirdParty/VNL/src/vxl/CMakeLists.txt:28 (cmake_policy):
  The OLD behavior for policy CMP0033 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Performing Test ITK_PRIVATE_DYNAMIC_CAST - Success
-- Checking for InitOnceExecuteOnce:
-- Performing Test InitOnceExecuteOnce - Success
-- Filter ZLIB is ON
-- Configuring done
-- Generating done
-- Build files have been written to: D:/mantis/ITKStuff/Build.PCWIN64/ITK-build
[6/17] Performing build step for 'ITK'
FAILED: ITK-prefix/src/ITK-stamp/ITK-build
cmd.exe /C "cd /D D:\mantis\ITKStuff\Build.PCWIN64\ITK-build && C:\msys64\mingw64\bin\cmake.exe --build . && C:\msys64\mingw64\bin\cmake.exe -E touch D:/mantis/ITKStuff/Build.PCWIN64/ITK-prefix/src/ITK-stamp/ITK-build"
[1/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zlassq.c.obj
[2/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zrot.c.obj
[3/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zung2r.c.obj
[4/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zlaset.c.obj
[5/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zunghr.c.obj
[6/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zlacn2.c.obj
[7/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zlatdf.c.obj
[8/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/ztgexc.c.obj
[9/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zungqr.c.obj
[10/1909] Building CXX object Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/vcl_deprecated.cxx.obj
FAILED: Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/vcl_deprecated.cxx.obj
c:\msys64\mingw64\bin\c++.exe  -DVXL_LEGACY_ERROR_REPORTING -DVXL_WARN_DEPRECATED -DVXL_WARN_DEPRECATED_ONCE -ID:/mantis/ITKStuff/Build.PCWIN64/ITK/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -ID:/mantis/ITKStuff/Build.PCWIN64/ITK/Modules/ThirdParty/VNL/src/vxl/vcl -ID:/mantis/ITKStuff/Build.PCWIN64/ITK/Modules/ThirdParty/VNL/src/vxl/core -IModules/ThirdParty/VNL/src/vxl/v3p/netlib -IModules/ThirdParty/VNL/src/vxl/vcl -IModules/ThirdParty/VNL/src/vxl/core -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow -Wno-deprecated -Wno-invalid-offsetof -Woverloaded-virtual -Wstrict-null-sentinel  -msse2 -mthreads -w  -O3 -DNDEBUG -MD -MT Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/vcl_deprecated.cxx.obj -MF Modules\ThirdParty\VNL\src\vxl\vcl\CMakeFiles\itkvcl.dir\vcl_deprecated.cxx.obj.d -o Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/vcl_deprecated.cxx.obj -c D:/mantis/ITKStuff/Build.PCWIN64/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_deprecated.cxx
In file included from D:/mantis/ITKStuff/Build.PCWIN64/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_iostream.h:5,
                 from D:/mantis/ITKStuff/Build.PCWIN64/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_deprecated.cxx:4:
D:/mantis/ITKStuff/Build.PCWIN64/ITK/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_compiler.h:90:4: error: #error "Dunno about this gcc"
   90 | #  error "Dunno about this gcc"
      |    ^~~~~
[11/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zggbak.c.obj
[12/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/ztrevc.c.obj
[13/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zgetc2.c.obj
[14/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/ztgsy2.c.obj
[15/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/ztgsyl.c.obj
[16/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zlatrs.c.obj
[17/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zgges.c.obj
[18/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zlaswp.c.obj
[19/1909] Building C object Modules/ThirdParty/VNL/src/vxl/v3p/netlib/CMakeFiles/itkv3p_netlib.dir/lapack/complex16/zhgeqz.c.obj
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.

I tried changing the ITK version in "External_ITKv4.cmake" to v4.13.2 or v5.0.1, but it does not help.

What can I do to make the compilation works? Please let me know if you need more details.

Many thanks,
Dengrong

**Comment by richardbeare** [comment]
Seems this problem has been encountered elsewhere - not yet sure if there is a solution:

https://discourse.itk.org/t/building-and-compiling-with-gcc-8-1/934/7

**Comment by Tet5329** [comment]
Hi, I also had a problem at msys on Windows10.

$ ninja
[1/16] Performing download step (git clone) for 'ITK'
FAILED: ITK-prefix/src/ITK-stamp/ITK-download
cmd.exe /C "cd /D C:\msys64\home\t\mantis\ITKStuff\Build.PCWIN64 && C:\msys64\mingw64\bin\cmake.exe -P C:/msys64/home/t/mantis/ITKStuff/Build.PCWIN64/ITK-prefix/tmp/ITK-gitclone.cmake && C:\msys64\mingw64\bin\cmake.exe -E touch C:/msys64/home/t/mantis/ITKStuff/Build.PCWIN64/ITK-prefix/src/ITK-stamp/ITK-download"
Cloning into 'ITK'...
fatal: unable to connect to itk.org:
itk.org[0: 66.194.253.19]: errno=Connection timed out

Cloning into 'ITK'...
fatal: unable to connect to itk.org:
itk.org[0: 66.194.253.19]: errno=Connection timed out

Cloning into 'ITK'...
fatal: unable to connect to itk.org:
itk.org[0: 66.194.253.19]: errno=Connection timed out

-- Had to git clone more than once:
          3 times.
CMake Error at ITK-prefix/tmp/ITK-gitclone.cmake:31 (message):
  Failed to clone repository: 'git://itk.org/ITK.git'


ninja: build stopped: subcommand failed.

Please give some advice.

Tet

**Comment by richardbeare** [comment]
Hi,
Thanks for your interest. We are in the process of updating but are awaiting some feedback on testing. Do the following, if you would like to try the new version:

```bash
git clone https://github.com/DevelopmentalImagingMCRI/mantis.git
cd mantis
git checkout BumpITKVersion
git submodule init
git submodule update
```

And then proceed as before. This fetches a modified ITK that uses an updated version of the ParabolicMorphology module.

Let me know how you go.

**Comment by Tet5329** [comment]
Thank you for acknowledgement.
I tried, but still error appears as below.

$ git submodule update
Cloning into '/home/T/mantis/ITKStuff/tclap-code'...
fatal: unable to connect to git.code.sf.net:
git.code.sf.net[0: 216.105.38.16]: errno=Connection timed out

fatal: clone of 'git://git.code.sf.net/p/tclap/code' into submodule path '/home/T/mantis/ITKStuff/tclap-code' failed
Failed to clone 'ITKStuff/tclap-code'. Retry scheduled
Cloning into '/home/T/mantis/ITKStuff/tclap-code'...
fatal: unable to connect to git.code.sf.net:
git.code.sf.net[0: 216.105.38.16]: errno=Connection timed out

fatal: clone of 'git://git.code.sf.net/p/tclap/code' into submodule path '/home/T/mantis/ITKStuff/tclap-code' failed
Failed to clone 'ITKStuff/tclap-code' a second time, aborting

**Comment by richardbeare** [comment]
Hi,
This is a different error. Hopefully it is temporary. I can't find anything to suggest that the path for that repo has changed.

**Comment by Tet5329** [comment]
Thank you for advice.

By the way. I do not understand in the following instruction;
"Create the build folder. PCWIN64, in the paths below, is the result of the matlab command:
computer".

Could you explain?

**Comment by richardbeare** [comment]
For the other platforms we run the command:
```bash
export ARCH=$(echo "disp(sprintf('\n%s', computer)),quit" | matlab -nojvm -nodesktop -nosplash |tail -1)
```
The runs the "computer" command inside matlab in order use the result of that command in the name of the directory. We haven't tested an equivalent command fro msys2, so try running it manually.

Fire up matlab on the machine you are using, run "computer" and check the result. Hopefully it will be PCWIN64. If it isn't then replace PCWIN64 with the result you do get wherever PCWIN64 appears in the instructions.

**Comment by Tet5329** [comment]
Thanks again.
I had error on Windows again.
So, I tried it on Ubuntu 18. It seemed the compile had completed.
I will try on SPM.

**Comment by richardbeare** [comment]
Was it the same error (retrieving tclap) or something else?

**Comment by Tet5329** [comment]
The errors on Windows was as follows:

$ ninja
[1/13] Performing configure step for 'ITK'
FAILED: ITK-prefix/src/ITK-stamp/ITK-configure
cmd.exe /C "cd /D C:\msys64\home\T\mantis\ITKStuff\Build.PCWIN64\ITK-build && C:\msys64\mingw64\bin\cmake.exe --no-warn-unused-cli -C C:/msys64/home/T/mantis/ITKStuff/Build.PCWIN64/ITK-build/CMakeCacheInit.txt -DMAKECOMMAND:= -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER:FILEPATH=C:/msys64/mingw64/bin/cc.exe -DCMAKE_C_FLAGS_DEBUG:STRING=-g "-DCMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG" "-DCMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG" "-DCMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG" -DCMAKE_CXX_COMPILER:UNINITIALIZED=c:/msys64/mingw64/bin/c++.exe -DCMAKE_CXX_FLAGS_DEBUG:STRING=-g "-DCMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG" "-DCMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG" "-DCMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG" "-DCMAKE_EXE_LINKER_FLAGS:STRING=-static-libgcc -static-libstdc++ -static -lpthread" -DCMAKE_GENERATOR:INTERNAL=Ninja -DMEMORYCHECK_COMMAND_OPTIONS:= -DMEMORYCHECK_SUPPRESSIONS_FILE:= -DMEMORYCHECK_COMMAND:= -DSITE:=NoSiteGiven -DBUILDNAME:=NoBuldNameGiven -DBUILD_EXAMPLES:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF -DBUILD_TESTING:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_SKIP_RPATH:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=C:/msys64/home/T/mantis/ITKStuff/Build.PCWIN64/ITK-prefix -DITK_LEGACY_REMOVE:BOOL=ON -DITK_BUILD_DEFAULT_MODULES:BOOL=ON -DModule_ParabolicMorphology=ON -DModule_ITKReview:BOOL=ON -DUSE_WRAP_ITK:BOOL=OFF -DINSTALL_WRAP_ITK_COMPATIBILITY:BOOL=OFF -GNinja C:/msys64/home/T/mantis/ITKStuff/Build.PCWIN64/ITK && C:\msys64\mingw64\bin\cmake.exe -E touch C:/msys64/home/T/mantis/ITKStuff/Build.PCWIN64/ITK-prefix/src/ITK-stamp/ITK-configure"
Not searching for unused variables given on the command line.
loading initial cache file C:/msys64/home/T/mantis/ITKStuff/Build.PCWIN64/ITK-build/CMakeCacheInit.txt
CMake Error at CMakeLists.txt:118 (message):
  ITK build directory path length is too long (56 > 50).Please set the ITK
  build directory to a directory with a shorter path.


-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/T/mantis/ITKStuff/Build.PCWIN64/ITK-build/CMakeFiles/CMakeOutput.log".
ninja: build stopped: subcommand failed.

**Comment by richardbeare** [comment]
That is a pain. I had forgotten about that. The only option is to create a working folder in the root of a drive and use a short name, for example /c/M, and put mantis in there for the build process.

**Comment by Tet5329** [comment]
This time, the  complite substaintially proceeded. However, the error appeared at last.

[5/10] Building CXX object CMakeFiles/compareMasksSurf.dir/compareMasksSurf.cxx.obj
FAILED: CMakeFiles/compareMasksSurf.dir/compareMasksSurf.cxx.obj
c:\msys64\mingw64\bin\c++.exe  -DITK_IO_FACTORY_REGISTER_MANAGER -DNDEBUG -IITKFactoryRegistration -I../../ -I../../tclap-code/include -isystem ../ITK-prefix/include/ITK-5.2 -isystem ../ITK-prefix/include/ITK-5.2/Utilities -isystem ../ITK-prefix/include -Wno-long-long -Wextra -Wformat=2 -Wno-format-nonliteral -Wunused -Wpointer-arith -Winvalid-pch -Wcast-align -Wdisabled-optimization -Woverloaded-virtual -Wshadow -Wwrite-strings -Wstrict-null-sentinel -Wno-invalid-offsetof  -mthreads -O3 -DNDEBUG -MD -MT CMakeFiles/compareMasksSurf.dir/compareMasksSurf.cxx.obj -MF CMakeFiles\compareMasksSurf.dir\compareMasksSurf.cxx.obj.d -o CMakeFiles/compareMasksSurf.dir/compareMasksSurf.cxx.obj -c ../../compareMasksSurf.cxx
../../compareMasksSurf.cxx:2:10: fatal error: tclap/CmdLine.h: No such file or directory
    2 | #include "tclap/CmdLine.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.

Do you think ubuntu-compiled mantis can be available in Windows-SPM?

**Comment by Tet5329** [comment]
As you commented. a short name for Mantis was effective and seemed to completed.
I used in Matlab.
The following error appeared.
Your advice would be appreciated.

Failed  'Watershed segmentation of CSF'
error: read_hdr (line 39)
Error reading header file "C:\Users\T\Documents\MATLAB\neot2\Phase2\btemp8_csfmask.nii".
In file "C:\Users\T\Documents\MATLAB\spm12\@nifti\private\read_hdr.m" (v7504), function "read_hdr" at line 39.
In file "C:\Users\T\Documents\MATLAB\spm12\@nifti\nifti.m" (v7758), function "nifti" at line 26.
In file "C:\Users\T\Documents\MATLAB\spm12\spm_get_space.m" (v6379), function "spm_get_space" at line 18.
In file "C:\Users\T\Documents\MATLAB\spm12\toolbox\mantis\mantisCopyHeader.m" (???), function "mantisCopyHeader" at line 5.
In file "C:\Users\T\Documents\MATLAB\spm12\toolbox\mantis\cg_mantis_ws_csf_run.m" (???), function "cg_mantis_ws_csf_run" at line 33.

**Comment by richardbeare** [comment]
An ubuntu compilation definitely won't work under windows.
Did you get the compilation to complete without any error? If not then I'd expect errors when running.

The error about tclap is an important one and presumably means that the download of the tclap code didn't work. I just tested the cloning steps and the tclap code appears to have been successfully fetched, so perhaps try that again and confirm that the compilation is OK, as it definitely won't work if you have errors like
```bash
compilation terminated.
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.

```

**Comment by Tet5329** [comment]
msys seemed successfully compiled.

[17/17] Completed 'MANTiS'

I confirmed .exe files at mantis/ITKStuff/Build.PCWIN64/MANTiS-build/bin/.

Thank you. Nest step is SPM.
